### ISSUE TITLE
USER STORY: Add comment to vote.

### ISSUE THREAD

**Issue by EwanColquhoun** [EwanColquhoun/love-running#2]
In order to **explain my choice** as a **user**, I can **comment on why I have chosen that particular track as my favourite**.

### Acceptance Criteria
- Option to add a comment
- Option to edit and/or delete a comment once it is posted.

### Tasks
- [ ] Add a text area
- [ ] Add a submit button for the text area
- [ ] Add an edit function once submitted
- [ ] Add HTML and CSS for all elements
